files:
  - source: /src/config/locales/messages.pot
    translation: /src/config/locales/%two_letters_code%.po
    languages_mapping:
      two_letters_code:
        zh-CN: zh_cn
        zh-TW: zh_tw
